name: khushu
base: core24
version: '1.0.0'
title: Khushu
summary: An all-in-one Muslim app for Linux.
description: |
  Khushu is your all-in-one Muslim app for Linux desktop, tablets, and smartphones.
  It centralizes your daily worship by providing accurate prayer times, native staggered Adkar notifications, and a roadmap that includes a dedicated Holy Quran experience—all with uncompromising privacy and zero telemetry.
license: GPL-3.0-or-later
website: https://github.com/sniper1720/khushu
issues: https://github.com/sniper1720/khushu/issues
source-code: https://github.com/sniper1720/khushu
donation: https://github.com/sponsors/sniper1720

grade: stable
confinement: strict
icon: data/icons/hicolor/scalable/apps/io.github.sniper1720.khushu.svg

slots:
  dbus-khushu:
    interface: dbus
    bus: session
    name: io.github.sniper1720.khushu

apps:
  khushu:
    command: usr/bin/khushu
    desktop: usr/share/applications/io.github.sniper1720.khushu.desktop
    autostart: io.github.sniper1720.khushu.desktop
    common-id: io.github.sniper1720.khushu
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - unity7
      - location-observe
    slots:
      - dbus-khushu

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/asound.conf:
    bind-file: $SNAP/assets/asound.conf

parts:
  khushu:
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    source: .
    build-snaps:
      - rustup
    build-packages:
      - gettext
      - build-essential
      - pkg-config
      - libgtk-4-dev
      - libadwaita-1-dev
      - libgeoclue-2-dev
    stage-packages:
      - ca-certificates
      - libasound2t64
      - libpulse0
      - alsa-utils
      - libasound2-plugins
      - libayatana-appindicator3-1
    override-build: |
      rustup default stable
      export PATH="$HOME/.cargo/bin:$PATH"

      craftctl default
      
      # --- Fix GNOME Library Conflicts ---
      rm -f $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libharfbuzz*.so*
      rm -f $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpango*.so*
      rm -f $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/librsvg*.so*

      # --- ALSA config ---
      mkdir -p $CRAFT_PART_INSTALL/assets
      echo -e "pcm.!default { type pulse }\nctl.!default { type pulse }" > $CRAFT_PART_INSTALL/assets/asound.conf
